# Generated by Django 2.0.7 on 2018-11-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_at_canteen', '0002_auto_20181102_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Add_a_Review',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
