# Generated by Django 2.1.1 on 2018-11-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_at_canteen', '0007_order_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER_FOOD',
        ),
    ]
