# Generated by Django 2.1.2 on 2018-11-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_at_canteen', '0008_delete_order_food'),
        ('eat_at_canteen', '0007_review_user_review'),
    ]

    operations = [
    ]
