# Generated by Django 2.1.2 on 2018-12-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_at_canteen', '0009_merge_20181127_1613'),
        ('eat_at_canteen', '0009_merge_20181119_1152'),
    ]

    operations = [
    ]
