# Generated by Django 2.1.2 on 2018-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='canteen_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='canteen_pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='canteen_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
