# Generated by Django 2.1.2 on 2018-11-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20181102_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='user_profile_pics'),
        ),
    ]
