# Generated by Django 2.1.2 on 2018-11-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
