# Generated by Django 2.1.2 on 2018-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_remove_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
