# Generated by Django 2.1.2 on 2018-11-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
