# Generated by Django 2.1.2 on 2018-11-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
    ]
