# Generated by Django 2.1.2 on 2018-11-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
