# Generated by Django 2.1.2 on 2018-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='new2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
