# Generated by Django 2.1.2 on 2018-11-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_new2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodorders',
        ),
    ]
