# Generated by Django 2.1.2 on 2018-10-29 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HD_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('dNo', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='HD_FoodOrder',
            fields=[
                ('tokenId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateTimeField()),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items')),
            ],
        ),
        migrations.AddField(
            model_name='hd_address',
            name='tokenId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homedelivery.HD_FoodOrder'),
        ),
    ]
