# Generated by Django 2.1.2 on 2018-11-17 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homedelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hd_address',
            name='town',
            field=models.CharField(choices=[('Sri City', 'Sri City')], default='Sri City', max_length=225),
        ),
        migrations.AlterField(
            model_name='hd_foodorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
