# Generated by Django 2.1.1 on 2018-11-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedelivery', '0002_auto_20181117_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hd_foodorder',
            name='Food_id',
        ),
        migrations.AlterField(
            model_name='hd_address',
            name='dNo',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='hd_address',
            name='tokenId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Order_User'),
        ),
        migrations.DeleteModel(
            name='HD_FoodOrder',
        ),
    ]
