# Generated by Django 2.1.2 on 2018-11-19 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_auto_20181117_1129'),
        ('homedelivery', '0003_auto_20181118_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='HD_FoodOrder',
            fields=[
                ('tokenId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items')),
            ],
        ),
        migrations.AlterField(
            model_name='hd_address',
            name='tokenId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homedelivery.HD_FoodOrder'),
        ),
    ]
