# Generated by Django 2.1.2 on 2018-10-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Towns', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food_items',
            fields=[
                ('Food_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Food_Name', models.CharField(max_length=225, unique=True)),
                ('Food_Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('Table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
