# Generated by Django 2.1.2 on 2018-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='Food_Name',
            field=models.CharField(max_length=225),
        ),
    ]
