# Generated by Django 2.1.2 on 2018-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20181030_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='Category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
