# Generated by Django 2.1.1 on 2018-11-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_food_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dining_Tables',
            fields=[
                ('Table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('availability', models.BooleanField(default=True)),
                ('size', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='Food_id',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.AddField(
            model_name='available_towns',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food_items',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food_items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
