# Generated by Django 2.1.1 on 2018-11-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20181110_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining_tables',
            name='zone',
            field=models.CharField(default='Normal', max_length=225),
        ),
    ]
