# Generated by Django 2.1.1 on 2018-11-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_dining_tables_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining_tables',
            name='zone',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Party', 'Party'), ('Family', 'Family')], default='Normal', max_length=10),
        ),
    ]
