# Generated by Django 2.1.2 on 2018-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_auto_20181111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='image',
            field=models.ImageField(null=True, upload_to='static/Manager/Foodimg/'),
        ),
    ]
